version: '3.8'

services:
  php_blue:
    container_name: php_blue
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel

  php_green:
    container_name: php_green
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    container_name: mysql
    restart: unless-stopped
    tty: true
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=multi_vendor
      - MYSQL_USER=abdo
      - MYSQL_PASSWORD=78957895
      - MYSQL_ROOT_PASSWORD=78957895
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php_blue
      - php_green
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
