name: Deploy multi vendor 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: multi_vendor
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/multi_vendor/multi_vendor
          ./docker/redeploy.sh


