name: Deploy multi vendor 

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      use: actions/checkout@v4

    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        # password: ${{ secrets.SSH_PASSWORD }}
      script: |
        cd ${{ secrets.APP_PATH }}
        ./build.sh
