name: Deploy multi vendor 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: 13.49.21.197
        username: auto_wash
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/auto_wash
          ./redeploy.sh